spring.application.name=trackify
server.port=8081

# YouTube Data API v3
youtube.api.key=AIzaSyB8PcLrJWw0S7QAOzxsetBf3_I1mVTYO6c

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/trackify?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Prajwal123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null
